import { ref } from "vue";

import type { Product } from "./product.type";
import { ProductCategoryEnum } from "./productCategory.enum";

export const productsList = ref<Product[]>([
  {
    id: 1,
    name: "Laptop",
    description: "Powerful laptop",
    price: 1499,
    category: ProductCategoryEnum.Electronics,
    image: "laptop.jpg",
  },
  {
    id: 2,
    name: "Smartphone",
    description: "Latest generation phone",
    price: 799,
    category: ProductCategoryEnum.Electronics,
    image: "smartphone.jpg",
  },
  {
    id: 3,
    name: "Office chair",
    description: "Comfortable chair for work",
    price: 199,
    category: ProductCategoryEnum.Furniture,
    image: "office-chair.webp",
  },
  {
    id: 4,
    name: "Desk lamp",
    description: "Light up your desk",
    price: 49,
    category: ProductCategoryEnum.Decoration,
    image: "lamp.jpg",
  },
  {
    id: 5,
    name: "Vue.js book",
    description: "Learn Vue.js quickly",
    price: 29,
    category: ProductCategoryEnum.Books,
    image: "book.jpg",
  },
  {
    id: 6,
    name: "Standing Desk",
    description: "Ergonomic desk for standing work",
    price: 499,
    category: ProductCategoryEnum.Furniture,
    image: "standing-desk.webp",
  },
  {
    id: 7,
    name: "Refrigerator",
    description: "Energy-efficient fridge",
    price: 899,
    category: ProductCategoryEnum.Appliances,
    image: "fridge.jpg",
  },
  {
    id: 8,
    name: "Microwave Oven",
    description: "Quick and efficient cooking",
    price: 129,
    category: ProductCategoryEnum.Appliances,
    image: "microwave.jpg",
  },
  {
    id: 9,
    name: "Coffee Table",
    description: "Modern wooden coffee table",
    price: 149,
    category: ProductCategoryEnum.Furniture,
    image: "coffee-table.jpg",
  },
  {
    id: 10,
    name: "Canvas Wall Art",
    description: "Beautiful abstract art for your wall",
    price: 89,
    category: ProductCategoryEnum.Decoration,
    image: "canvas-art.jpg",
  },
  {
    id: 11,
    name: "Bluetooth Headphones",
    description: "Noise-cancelling over-ear headphones",
    price: 249,
    category: ProductCategoryEnum.Electronics,
    image: "headphones.jpg",
  },
  {
    id: 12,
    name: "Leather Sofa",
    description: "Elegant and comfortable sofa",
    price: 1099,
    category: ProductCategoryEnum.Furniture,
    image: "leather-sofa.jpg",
  },
  {
    id: 13,
    name: "Air Conditioner",
    description: "Cool down your summer",
    price: 699,
    category: ProductCategoryEnum.Appliances,
    image: "air-conditioner.jpg",
  },
  {
    id: 14,
    name: "Cookbook: World Cuisine",
    description: "Explore global recipes",
    price: 39,
    category: ProductCategoryEnum.Books,
    image: "cookbook.jpg",
  },
  {
    id: 15,
    name: "Gaming Monitor",
    description: "144Hz ultra HD screen",
    price: 349,
    category: ProductCategoryEnum.Electronics,
    image: "gaming-monitor.jpg",
  },
  {
    id: 16,
    name: "Bookshelf",
    description: "Spacious 5-tier wooden shelf",
    price: 179,
    category: ProductCategoryEnum.Furniture,
    image: "bookshelf.jpg",
  },
  {
    id: 17,
    name: "Floor Lamp",
    description: "Stylish floor lamp with LED",
    price: 89,
    category: ProductCategoryEnum.Decoration,
    image: "floor-lamp.jpg",
  },
  {
    id: 18,
    name: "Electric Kettle",
    description: "Boil water in minutes",
    price: 59,
    category: ProductCategoryEnum.Appliances,
    image: "kettle.jpg",
  },
  {
    id: 19,
    name: "Productivity Journal",
    description: "Plan your day efficiently",
    price: 19,
    category: ProductCategoryEnum.Books,
    image: "journal.jpg",
  },
  {
    id: 20,
    name: "Gaming Chair",
    description: "Ergonomic chair with lumbar support",
    price: 299,
    category: ProductCategoryEnum.Furniture,
    image: "gaming-chair.jpg",
  },
]);
