name: Deploy to VPS

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.JS version 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm run build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: production-files
        path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: production-files
        path: ./build

    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY_GITHUB_ACTIONS: ${{ secrets.SSH_PRIVATE_KEY_GITHUB_ACTIONS }}
        SSH_VPS_USER: ${{ secrets.SSH_VPS_USER }}
        SSH_VPS_HOST: ${{ secrets.SSH_VPS_HOST }}
        SSH_VPS_PROJECT_LOCATION: ${{ secrets.SSH_VPS_PROJECT_LOCATION }}

      run: |
        echo "$SSH_PRIVATE_KEY_GITHUB_ACTIONS" > key.pem
        chmod 600 key.pem
        ssh -i key.pem -o StrictHostKeyChecking=no $SSH_VPS_USER@$SSH_VPS_HOST "rm -rf $SSH_VPS_PROJECT_LOCATION*"
        rsync -az --delete -e "ssh -i key.pem -o StrictHostKeyChecking=no" build/ $SSH_VPS_USER@$SSH_VPS_HOST:$SSH_VPS_PROJECT_LOCATION
